import { CategoryKorType } from '@/types/common';

export const CATEGORIES: Array<CategoryKorType> = [
  '전체',
  '근처',
  '추천',
  '먹거리',
  '관광',
  '야외 활동',
  '놀거리',
  '문화예술',
  '스포츠/운동',
];

const countries = [
  { name: '가나', alpha3: 'GHA', code: '+233' },
  { name: '가봉', alpha3: 'GAB', code: '+241' },
  { name: '가이아나', alpha3: 'GUY', code: '+592' },
  { name: '감비아', alpha3: 'GMB', code: '+220' },
  { name: '그레나다', alpha3: 'GRD', code: '+1 473' },
  { name: '기니', alpha3: 'GIN', code: '+224' },
  { name: '기니비사우', alpha3: 'GNB', code: '+245' },
  { name: '나미비아', alpha3: 'NAM', code: '+264' },
  { name: '나이지리아', alpha3: 'NGA', code: '+234' },
  { name: '네덜란드', alpha3: 'NLD', code: '+31' },
  { name: '네덜란드령 안틸레스', alpha3: 'ANT', code: '+599' },
  { name: '노르웨이', alpha3: 'NOR', code: '+47' },
  { name: '뉴질랜드', alpha3: 'NZL', code: '+64' },
  { name: '니제르', alpha3: 'NER', code: '+227' },
  { name: '니카라과', alpha3: 'NIC', code: '+505' },
  { name: '대한민국', alpha3: 'KOR', code: '+82' },
  { name: '덴마크', alpha3: 'DNK', code: '+45' },
  { name: '도미니카 공화국', alpha3: 'DOM', code: '+1 809' },
  { name: '독일', alpha3: 'DEU', code: '+49' },
  { name: '동티모르', alpha3: 'TLS', code: '+670' },
  { name: '라이베리아', alpha3: 'LBR', code: '+231' },
  { name: '라트비아', alpha3: 'LVA', code: '+371' },
  { name: '러시아', alpha3: 'RUS', code: '+7' },
  { name: '레바논', alpha3: 'LBN', code: '+961' },
  { name: '레소토', alpha3: 'LSO', code: '+266' },
  { name: '루마니아', alpha3: 'ROU', code: '+40' },
  { name: '룩셈부르크', alpha3: 'LUX', code: '+352' },
  { name: '르완다', alpha3: 'RWA', code: '+250' },
  { name: '리비아', alpha3: 'LBY', code: '+218' },
  { name: '리투아니아', alpha3: 'LTU', code: '+370' },
  { name: '말라위', alpha3: 'MWI', code: '+265' },
  { name: '말레이시아', alpha3: 'MYS', code: '+60' },
  { name: '말리', alpha3: 'MLI', code: '+223' },
  { name: '멕시코', alpha3: 'MEX', code: '+52' },
  { name: '모로코', alpha3: 'MAR', code: '+212' },
  { name: '모리셔스', alpha3: 'MUS', code: '+230' },
  { name: '모리타니', alpha3: 'MRT', code: '+222' },
  { name: '모잠비크', alpha3: 'MOZ', code: '+258' },
  { name: '몬테네그로', alpha3: 'MNE', code: '+382' },
  { name: '몰디브', alpha3: 'MDV', code: '+960' },
  { name: '몰타', alpha3: 'MLT', code: '+356' },
  { name: '몽골', alpha3: 'MNG', code: '+976' },
  { name: '미국', alpha3: 'USA', code: '+1' },
  { name: '미얀마', alpha3: 'MMR', code: '+95' },
  { name: '베냉', alpha3: 'BEN', code: '+229' },
  { name: '베네수엘라', alpha3: 'VEN', code: '+58' },
  { name: '벨기에', alpha3: 'BEL', code: '+32' },
  { name: '벨라루스', alpha3: 'BLR', code: '+375' },
  { name: '보스니아 헤르체고비나', alpha3: 'BIH', code: '+387' },
  { name: '보츠와나', alpha3: 'BWA', code: '+267' },
  { name: '볼리비아', alpha3: 'BOL', code: '+591' },
  { name: '부룬디', alpha3: 'BDI', code: '+257' },
  { name: '부르키나파소', alpha3: 'BFA', code: '+226' },
  { name: '부탄', alpha3: 'BTN', code: '+975' },
  { name: '북마리아나 제도', alpha3: 'MNP', code: '+1 670' },
  { name: '불가리아', alpha3: 'BGR', code: '+359' },
  { name: '브라질', alpha3: 'BRA', code: '+55' },
  { name: '브루나이', alpha3: 'BRN', code: '+673' },
  { name: '사모아', alpha3: 'WSM', code: '+685' },
  { name: '사우디아라비아', alpha3: 'SAU', code: '+966' },
  { name: '산마리노', alpha3: 'SMR', code: '+378' },
  { name: '상투메 프린시페', alpha3: 'STP', code: '+239' },
  { name: '세네갈', alpha3: 'SEN', code: '+221' },
  { name: '세르비아', alpha3: 'SRB', code: '+381' },
  { name: '세이셸', alpha3: 'SYC', code: '+248' },
  { name: '세인트루시아', alpha3: 'LCA', code: '+1 758' },
  { name: '세인트빈센트 그레나딘', alpha3: 'VCT', code: '+1 784' },
  { name: '세인트키츠 네비스', alpha3: 'KNA', code: '+1 869' },
  { name: '소말리아', alpha3: 'SOM', code: '+252' },
  { name: '솔로몬 제도', alpha3: 'SLB', code: '+677' },
  { name: '수단', alpha3: 'SDN', code: '+249' },
  { name: '수리남', alpha3: 'SUR', code: '+597' },
  { name: '스리랑카', alpha3: 'LKA', code: '+94' },
  { name: '스웨덴', alpha3: 'SWE', code: '+46' },
  { name: '스위스', alpha3: 'CHE', code: '+41' },
  { name: '스페인', alpha3: 'ESP', code: '+34' },
  { name: '슬로바키아', alpha3: 'SVK', code: '+421' },
  { name: '슬로베니아', alpha3: 'SVN', code: '+386' },
  { name: '시에라리온', alpha3: 'SLE', code: '+232' },
  { name: '싱가포르', alpha3: 'SGP', code: '+65' },
  { name: '아랍에미리트', alpha3: 'ARE', code: '+971' },
  { name: '아르메니아', alpha3: 'ARM', code: '+374' },
  { name: '아르헨티나', alpha3: 'ARG', code: '+54' },
  { name: '아이슬란드', alpha3: 'ISL', code: '+354' },
  { name: '아이티', alpha3: 'HTI', code: '+509' },
  { name: '아일랜드', alpha3: 'IRL', code: '+353' },
  { name: '아제르바이잔', alpha3: 'AZE', code: '+994' },
  { name: '아프가니스탄', alpha3: 'AFG', code: '+93' },
  { name: '안도라', alpha3: 'AND', code: '+376' },
  { name: '알바니아', alpha3: 'ALB', code: '+355' },
  { name: '알제리', alpha3: 'DZA', code: '+213' },
  { name: '앙골라', alpha3: 'AGO', code: '+244' },
  { name: '앤티가 바부다', alpha3: 'ATG', code: '+1 268' },
  { name: '에리트레아', alpha3: 'ERI', code: '+291' },
  { name: '에스토니아', alpha3: 'EST', code: '+372' },
  { name: '에콰도르', alpha3: 'ECU', code: '+593' },
  { name: '에티오피아', alpha3: 'ETH', code: '+251' },
  { name: '엘살바도르', alpha3: 'SLV', code: '+503' },
  { name: '영국', alpha3: 'GBR', code: '+44' },
  { name: '예멘', alpha3: 'YEM', code: '+967' },
  { name: '오만', alpha3: 'OMN', code: '+968' },
  { name: '오스트레일리아', alpha3: 'AUS', code: '+61' },
  { name: '오스트리아', alpha3: 'AUT', code: '+43' },
  { name: '온두라스', alpha3: 'HND', code: '+504' },
  { name: '요르단', alpha3: 'JOR', code: '+962' },
  { name: '우간다', alpha3: 'UGA', code: '+256' },
  { name: '우루과이', alpha3: 'URY', code: '+598' },
  { name: '우즈베키스탄', alpha3: 'UZB', code: '+998' },
  { name: '우크라이나', alpha3: 'UKR', code: '+380' },
  { name: '이라크', alpha3: 'IRQ', code: '+964' },
  { name: '이란', alpha3: 'IRN', code: '+98' },
  { name: '이스라엘', alpha3: 'ISR', code: '+972' },
  { name: '이집트', alpha3: 'EGY', code: '+20' },
  { name: '이탈리아', alpha3: 'ITA', code: '+39' },
  { name: '인도', alpha3: 'IND', code: '+91' },
  { name: '인도네시아', alpha3: 'IDN', code: '+62' },
  { name: '일본', alpha3: 'JPN', code: '+81' },
  { name: '자메이카', alpha3: 'JAM', code: '+1 876' },
  { name: '잠비아', alpha3: 'ZMB', code: '+260' },
  { name: '적도 기니', alpha3: 'GNQ', code: '+240' },
  { name: '조선민주주의인민공화국', alpha3: 'PRK', code: '+850' },
  { name: '조지아', alpha3: 'GEO', code: '+995' },
  { name: '중앙아프리카 공화국', alpha3: 'CAF', code: '+236' },
  { name: '중화민국', alpha3: 'TWN', code: '+886' },
  { name: '중화인민공화국', alpha3: 'CHN', code: '+86' },
  { name: '지부티', alpha3: 'DJI', code: '+253' },
  { name: '짐바브웨', alpha3: 'ZWE', code: '+263' },
  { name: '차드', alpha3: 'TCD', code: '+235' },
  { name: '체코', alpha3: 'CZE', code: '+420' },
  { name: '칠레', alpha3: 'CHL', code: '+56' },
  { name: '카메룬', alpha3: 'CMR', code: '+237' },
  { name: '카보베르데', alpha3: 'CPV', code: '+238' },
  { name: '카자흐스탄', alpha3: 'KAZ', code: '+7' },
  { name: '카타르', alpha3: 'QAT', code: '+974' },
  { name: '캄보디아', alpha3: 'KHM', code: '+855' },
  { name: '캐나다', alpha3: 'CAN', code: '+1' },
  { name: '케냐', alpha3: 'KEN', code: '+254' },
  { name: '코모로', alpha3: 'COM', code: '+269' },
  { name: '코스타리카', alpha3: 'CRI', code: '+506' },
  { name: '코트디부아르', alpha3: 'CIV', code: '+225' },
  { name: '콜롬비아', alpha3: 'COL', code: '+57' },
  { name: '콩고 공화국', alpha3: 'COG', code: '+242' },
  { name: '콩고 민주 공화국', alpha3: 'COD', code: '+243' },
  { name: '쿠바', alpha3: 'CUB', code: '+53' },
  { name: '쿠웨이트', alpha3: 'KWT', code: '+965' },
  { name: '크로아티아', alpha3: 'HRV', code: '+385' },
  { name: '키르기스스탄', alpha3: 'KGZ', code: '+996' },
  { name: '키리바시', alpha3: 'KIR', code: '+686' },
  { name: '키프로스', alpha3: 'CYP', code: '+357' },
  { name: '타지키스탄', alpha3: 'TJK', code: '+992' },
  { name: '탄자니아', alpha3: 'TZA', code: '+255' },
  { name: '태국', alpha3: 'THA', code: '+66' },
  { name: '터키', alpha3: 'TUR', code: '+90' },
  { name: '토고', alpha3: 'TGO', code: '+228' },
  { name: '통가', alpha3: 'TON', code: '+676' },
  { name: '투르크메니스탄', alpha3: 'TKM', code: '+993' },
  { name: '투발루', alpha3: 'TUV', code: '+688' },
  { name: '튀니지', alpha3: 'TUN', code: '+216' },
  { name: '트리니다드 토바고', alpha3: 'TTO', code: '+1 868' },
  { name: '파나마', alpha3: 'PAN', code: '+507' },
  { name: '파라과이', alpha3: 'PRY', code: '+595' },
  { name: '파키스탄', alpha3: 'PAK', code: '+92' },
  { name: '파푸아뉴기니', alpha3: 'PNG', code: '+675' },
  { name: '팔라우', alpha3: 'PLW', code: '+680' },
  { name: '페루', alpha3: 'PER', code: '+51' },
  { name: '포르투갈', alpha3: 'PRT', code: '+351' },
  { name: '폴란드', alpha3: 'POL', code: '+48' },
  { name: '프랑스', alpha3: 'FRA', code: '+33' },
  { name: '피지', alpha3: 'FJI', code: '+679' },
  { name: '핀란드', alpha3: 'FIN', code: '+358' },
  { name: '필리핀', alpha3: 'PHL', code: '+63' },
  { name: '헝가리', alpha3: 'HUN', code: '+36' },
  { name: '홍콩', alpha3: 'HKG', code: '+852' },
];



export const countryCode = countries.map(country => country.code);
export const countryList = countries.map(country => ({ label: country.name, value: country.alpha3 }));